#ifndef __ZOO_CONFIG_H__
#define __ZOO_CONFIG_H__

// Configuration

#define ZOO_CONFIG_ENABLE_SOUND_PCM

#define ZOO_CONFIG_ENABLE_SIDEBAR_CLASSIC
#define ZOO_CONFIG_ENABLE_SIDEBAR_SLIM

#undef ZOO_CONFIG_USE_DOUBLE_FOR_MS

#endif /* __ZOO_CONFIG_H__ */
